  *Day 1 of Pandas*

In [10]:
import pandas as pd

In [12]:
data=pd.read_csv("./Data/data.csv")

In [13]:
data.head()

,sr.no.,province,division,district,households,population_2023,average_household_size,population_2017,growth_rate,area(km²),...,primary_girls_schools,secondary_boys_schools,secondary_girls_schools,high_boys_schools,high_girls_schools,Intermediate_boys_schools,Intermediate_girls_schools,total_boys_schools,total_girls_schools,total_schools
0,1,Balochistan,Kalat,Awaran,27808,178958,6.44,121821,6.64,29510,...,107,24,13,29,10,2,2,249,132,381
1,2,Balochistan,Kalat,Kalat,33415,272506,8.16,211201,4.35,6622,...,84,23,18,27,17,1,1,269,120,389
2,3,Balochistan,Kalat,Khuzdar,161594,997214,6.17,798896,3.78,35380,...,177,45,46,32,21,6,1,569,245,814
3,4,Balochistan,Kalat,Lasbela,115635,680977,5.89,576271,2.83,15153,...,124,46,29,27,11,4,4,507,168,675
4,5,Balochistan,Kalat,Mastung,43736,313271,7.16,265676,2.79,5896,...,94,24,31,18,18,2,0,268,143,411

In [14]:
data.columns

Index(['sr.no.', 'province', 'division', 'district', 'households',
       'population_2023', 'average_household_size', 'population_2017',
       'growth_rate', 'area(km²)', 'density_2023(people/km²)',
       'primary_boys_schools', 'primary_girls_schools',
       'secondary_boys_schools', 'secondary_girls_schools',
       'high_boys_schools', 'high_girls_schools', 'Intermediate_boys_schools',
       'Intermediate_girls_schools', 'total_boys_schools',
       'total_girls_schools', 'total_schools'],
      dtype='object')

In [15]:
data.columns.tolist()

['sr.no.',
 'province',
 'division',
 'district',
 'households',
 'population_2023',
 'average_household_size',
 'population_2017',
 'growth_rate',
 'area(km²)',
 'density_2023(people/km²)',
 'primary_boys_schools',
 'primary_girls_schools',
 'secondary_boys_schools',
 'secondary_girls_schools',
 'high_boys_schools',
 'high_girls_schools',
 'Intermediate_boys_schools',
 'Intermediate_girls_schools',
 'total_boys_schools',
 'total_girls_schools',
 'total_schools']

In [16]:
data.describe()

,sr.no.,households,population_2023,average_household_size,population_2017,growth_rate,area(km²),density_2023(people/km²),primary_boys_schools,primary_girls_schools,secondary_boys_schools,secondary_girls_schools,high_boys_schools,high_girls_schools,Intermediate_boys_schools,Intermediate_girls_schools,total_boys_schools,total_girls_schools,total_schools
count,136.000000,1.360000e+02,1.360000e+02,136.000000,1.360000e+02,136.000000,136.000000,136.000000,136.000000,136.000000,136.000000,136.000000,136.000000,136.000000,136.000000,136.000000,136.000000,136.000000,136.000000
mean,68.500000,2.819159e+05,1.775731e+06,6.451618,1.527093e+06,2.827574,6036.323529,1521.740000,579.588235,264.397059,51.860294,50.786765,64.617647,44.029412,10.647059,6.389706,706.713235,365.602941,1072.316176
std,39.403892,2.789400e+05,1.791408e+06,0.944771,1.540987e+06,1.542254,6802.861419,6036.440643,591.909008,207.461492,34.935321,51.258879,53.103959,51.681781,20.981660,8.071140,621.938128,292.229090,753.412205
min,1.000000,1.640000e+04,1.275710e+05,4.180000,9.705200e+04,0.230000,69.000000,6.020000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,34.750000,7.052575e+04,4.999090e+05,5.852500,4.326818e+05,2.077500,2289.000000,122.947500,239.250000,93.750000,24.750000,16.750000,27.000000,10.000000,3.000000,1.000000,321.250000,120.000000,469.750000
50%,68.500000,2.187750e+05,1.370099e+06,6.390000,1.216293e+06,2.460000,3709.500000,331.580000,378.000000,206.000000,46.000000,31.000000,53.000000,23.500000,6.500000,3.000000,540.500000,268.000000,864.000000
75%,102.250000,3.838998e+05,2.338289e+06,6.960000,1.942269e+06,2.875000,7492.000000,772.712500,641.750000,395.250000,72.500000,72.500000,84.250000,55.250000,12.000000,9.250000,788.000000,582.750000,1439.250000
max,136.000000,2.012526e+06,1.300414e+07,9.110000,1.111998e+07,9.510000,44748.000000,55396.010000,3375.000000,1068.000000,241.000000,281.000000,345.000000,300.000000,233.000000,51.000000,3684.000000,1367.000000,4269.000000

In [17]:
data.__annotations__

{'_accessors': 'set[str]',
 '_hidden_attrs': 'frozenset[str]',
 '_mgr': 'BlockManager | ArrayManager',
 '_constructor_sliced': 'Callable[..., Series]',
 '_AXIS_ORDERS': "list[Literal['index', 'columns']]",
 '_AXIS_TO_AXIS_NUMBER': 'dict[Axis, int]',
 '_info_axis_number': 'Literal[1]',
 '_info_axis_name': "Literal['columns']"}

In [18]:
data.isnull()

,sr.no.,province,division,district,households,population_2023,average_household_size,population_2017,growth_rate,area(km²),...,primary_girls_schools,secondary_boys_schools,secondary_girls_schools,high_boys_schools,high_girls_schools,Intermediate_boys_schools,Intermediate_girls_schools,total_boys_schools,total_girls_schools,total_schools
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
132,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
133,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
134,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
135,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
titanic=sns.load_dataset('titanic')

In [21]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True