In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=sns.load_dataset('titanic')

In [3]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [4]:
bins=[0,1,5,10,14,35,50,80]
labels=['infant','child','kids','teen','young','midde aged','aged']

In [24]:
df['age_grouped']=pd.cut(df['age'],bins=bins, labels=labels)

In [25]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone', 'age_grouped'],
      dtype='object')

In [28]:
df_01=df[['survived','class','fare']]

In [29]:
df_01

     survived   class     fare
0           0   Third   7.2500
1           1   First  71.2833
2           1   Third   7.9250
3           1   First  53.1000
4           0   Third   8.0500
..        ...     ...      ...
886         0  Second  13.0000
887         1   First  30.0000
888         0   Third  23.4500
889         1   First  30.0000
890         0   Third   7.7500

[891 rows x 3 columns]

In [30]:
df_02=df[df['class']=='First']

In [32]:
df_02.value_counts()

survived  pclass  sex     age   sibsp  parch  fare      embarked  class  who    adult_male  deck  embark_town  alive  alone  age_grouped
1         1       female  24.0  0      0      69.3000   C         First  woman  False       B     Cherbourg    yes    True   young          2
0         1       female  2.0   1      2      151.5500  S         First  child  False       C     Southampton  no     False  child          1
                          50.0  0      0      28.7125   C         First  woman  False       C     Cherbourg    no     True   midde aged     1
                          25.0  1      2      151.5500  S         First  woman  False       C     Southampton  no     False  young          1
                  male    19.0  1      0      53.1000   S         First  man    True        D     Southampton  no     False  young          1
                                                                                                                                           ..
1         1       male    51.0  0      0      26.5500   S         First  man    True        E     Southampton  yes    True   aged           1
                          52.0  0      0      30.5000   S         First  man    True        C     Southampton  yes    True   aged           1
                          56.0  0      0      35.5000   C         First  man    True        A     Cherbourg    yes    True   aged           1
                          60.0  1      1      79.2000   C         First  man    True        B     Cherbourg    yes    False  aged           1
                          80.0  0      0      30.0000   S         First  man    True        A     Southampton  yes    True   aged           1
Name: count, Length: 156, dtype: int64

In [33]:
df_02.info()

<class 'pandas.core.frame.DataFrame'>
Index: 216 entries, 1 to 889
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     216 non-null    int64
 1   pclass       216 non-null    int64
 2   sex          216 non-null    object
 3   age          186 non-null    float64
 4   sibsp        216 non-null    int64
 5   parch        216 non-null    int64
 6   fare         216 non-null    float64
 7   embarked     214 non-null    object
 8   class        216 non-null    category
 9   who          216 non-null    object
 10  adult_male   216 non-null    bool
 11  deck         175 non-null    category
 12  embark_town  214 non-null    object
 13  alive        216 non-null    object
 14  alone        216 non-null    bool
 15  age_grouped  186 non-null    category
dtypes: bool(2), category(3), float64(2), int64(4), object(5)
memory usage: 22.1+ KB

In [44]:
df_200=df[df['fare']>0]

In [45]:
df_200['class'].value_counts()

class
Third     487
First     211
Second    178
Name: count, dtype: int64